name: Verify Pull Request Labeling

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify PR Labels
        shell: python
        run: |
          import json
          labels = json.loads("""${{ toJson(github.event.pull_request.labels) }}""")
          labels = [x['name'] for x in labels]
          print("PR labels: {}".format(labels))
          expected_min_labels = ['NewTest', 'TestFix', 'NewTestForExisting', 'Other']
          if not any([x in expected_min_labels for x in labels]):
              raise ValueError("Expected minimum one label in {}".format(expected_min_labels))
          if 'NewTest' in labels:
              if not any([x in ['PendingOSM', 'AddedOSM'] for x in labels]):
                raise ValueError("When using 'NewTest', you need to add either 'PendingOSM' or 'AddedOSM' as well")
