name: Rubocop

on:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - '**.md'
      - 'doc/**/*'
      - 'gemfiles/**/gems/**/*'
      - 'measures/**/*'
      - 'python/**/*'
      - 'test/**/*'
      - 'update_eplus_compare/**/*'
      - 'weatherdata/**/*'
      - 'model/refbuildingtests/measures/**/*'

jobs:
  rubocop:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout for PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # Checkout the PR branch instead of the merge commit

    - name: Checkout for push
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'

    - name: Run rubocop
      id: rubocop
      uses: jmarrec/rubocop-composite-action@v1
      with:
        autocorrect: true
        commit-auto-correct: true
        rubocop-version: 0.81.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
